# Generated by Django 4.1 on 2022-08-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_title', models.CharField(max_length=255)),
                ('receipt_image', models.ImageField(upload_to='images/receipt_image')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('expense_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
    ]
