# Generated by Django 4.1 on 2022-08-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_expenseitem_invoiceexpensethrough_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='receipt_image',
            field=models.FileField(upload_to='images/receipt_image'),
        ),
    ]
