# Generated by Django 4.1 on 2022-08-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='receipt_image',
            field=models.ImageField(upload_to='images/receipt_image'),
        ),
    ]
